### ISSUE TITLE
[HELP] Skyblock Starter kit (items)

### ISSUE THREAD

**Issue by TheKillerTacos** [XenoNova/SkyBlockXT#10]
Skyblock Starter KIT
---------------------------
So in the code there are the following items:
 Melon seeds
* Cactus?
* Iron, //NOT NEEDED AS STARTER
* water, //2 waterbuckets
* lava, //1, for Stone Generator :D
* String, //NOT NEEDED!
* Seeds, // NOT NEEDED!*
* Sapling, // Ok, but we got a tree?

So this kit is NOTHING skyblock kit related, so i need Help with the FULL kit, im really busy like to look this up :P but i hope you can help me, soon ill add Custom Kits, so Owners can change the Default kit..

If possible, try to add MCPE Ids

>* because some Server Cores like Genesys, have Mob Spawning and AI, and there are also plugins, but since that, ill make a Switch, (on/off) so people with other Cores, like original PM, doesnt has this problem, you can get Seeds by killing Skeletons and using Bone Meal?

**Comment by MateiGamingYTB** [comment]
Add VIP kit and admin kit

**Comment by TheKillerTacos** [comment]
Hi Also I'll add a kit system. But I need to know the normal IDs. For skyblocl

**Comment by Skyladd** [comment]
The items i listed come default in other plugins. They are needed if you want the full "skyblock" experience. String for start, cactus to start a cactus farm which could possibly fuel the economy, etc. MY LIST IS GOOD XD

**Comment by TheKillerTacos** [comment]
ok, but iron might be available in the nether (i guess) and if the server owner makes a shop

**Comment by Skyladd** [comment]
Iron isnt in the nether lol. Iron will be mined from a resetting mine or bought from a shop. Just keep the list i made.
