### ISSUE TITLE
Can players destroy others's islands?

### ISSUE THREAD

**Issue by XiangZhao969** [XenoNova/SkyBlockXT#13]

**Comment by Skyladd** [comment]
Shouldnt be able to, but production has been put to a hault im assuming. There is only one person working on this plugin and he needs help, which i can only do so much.

**Comment by TheKillerTacos** [comment]
They will not be able to do so, im going to merge ImagicalCorp SkyBlock Plugin, WILL GIVE CREDIT, and Modify it as much as i can.

**Comment by Skyladd** [comment]
ImagicalCorp Skybock is also a remake of MyPlot with different generation. Some things will need to be changed though, such as possibly reverting their world generator and making it generate like MyPlot in its own world. Also in my opinion, we should drop the PVP mix and just make an epic skyblock plugin with better generation and more features like warps, teams, etc. It could be the one and only best skyblock plugin if you do it right

**Comment by TheKillerTacos** [comment]
ok, PVP Features will be Made after BETA (1.0.0)

**Comment by TheKillerTacos** [comment]
Closing this issue.
