### ISSUE TITLE
Plugin Status

### ISSUE THREAD

**Issue by SkygridRex** [XenoNova/SkyBlockXT#16]
I need to know the state of the plugin! What do you have developed so far?

**Comment by HyGlobalHD** [comment]
The plugin still in development and as the readme state that the plugin will realese on 15/04/2016.

**Comment by TheKillerTacos** [comment]
the plugin Actually does créate an island, as i told you with the video, by now its PRE-ALPHA, im going to edit the island generator so it creates de island with the diamond shaped (shown in README.md) and after that, you may help me with how to protect an área and how to fill chests

**Comment by SkygridRex** [comment]
I know how to Make chest refill but how to protect nope

**Comment by HyGlobalHD** [comment]
how about when player generate the island its claim automatically but unclaim when the player delete the island.i suggest take a peek on clqim code at plotme

**Comment by SkygridRex** [comment]
Could be

**Comment by SkygridRex** [comment]
Hahahahahaha

**Comment by Skyladd** [comment]
I see Byron has development help

**Comment by TheKillerTacos** [comment]
Hehe

**Comment by TheKillerTacos** [comment]
HyglobalHD, That's what I'll have to the to-do. Since I'll be looking to make an area for the skyblock and get it recorded so it can be reseted easly
