### ISSUE TITLE
[ERROR] Please help! idk what to do and is already getting late for PRE-ALPHA!

### ISSUE THREAD

**Issue by TheKillerTacos** [XenoNova/SkyBlockXT#19]
So i had been fixing a lot of errors and bugs and added few more features fixed generator and added empty world generator, it was time for testing so fixed more bugs, and now im stuck in here, The server drops this error every time i run it:

[Server thread/CRITICAL]: ClassNotFoundException: "Class SkyBlockXT\Tools\SkyWorld not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 115

and in the code its actually Importing it and also there is a SkyBlockXT\Tools\SkyWorld(.php)!
https://github.com/XenoNova/SkyBlockXT/blob/master/src/SkyBlockXT/Main.php#L23
https://github.com/XenoNova/SkyBlockXT/blob/master/src/SkyBlockXT/Tools/SkyWorld.php

https://github.com/XenoNova/SkyBlockXT/blob/master/src/SkyBlockXT/Tools/SkyWorld.php

@SkygridRex @Skyladd @AndreTheGamer @Adam1609 @thebigsmileXD Can you help out if possible? Also im asking this on PM:

**Comment by TheKillerTacos** [comment]
Fixed!

**Comment by SkygridRex** [comment]
No entendi ni un carajo mi ingles no da tanto

**Comment by TheKillerTacos** [comment]
Haha. Ya lo arregle
