### ISSUE TITLE
[NOTICE] Delay for PRE-ALPHA Release!

### ISSUE THREAD

**Issue by TheKillerTacos** [XenoNova/SkyBlockXT#21]
[NOTICE] Delay For Release:
============
Sorry, But the release of **PRE-ALPHA**, Will be **Delayed**, But Why?
Since Im having some important events going on (I might move to another house :D) by these days (15/04 to 26/04), So I might Not be going to update this plugin that frequently, so the Release doesnt has an exact date or time (isnt that the same?).

And Also since Im creating SkyLand (The Main island Generator) it will not be Updated by **Other**
Contributors in here, but also im Going to Implement SkyLand with SkyWorld, Since SkyLand can
**Only** Generate Islands on Created/Loaded Chunks, but SkyWorld only Generates empty Chunks
(Chunks filled with AIR) but doesnt  Populates the chunks, so it will now Populate chunks with an island (Like ImagicalMine SkyBlock plugin, but ill not use that code at all)

So that is 2 Points for the delay, Badly, but as soon as I have free time, ill continue developing
the plugin, And also Im busy creating a Minecraft World for an animation, and creating 
MCPC and MCPE servers (Yep, Tacos-World! or Universe? vote!)

Conclution: Yep, sorry for this little, bad, notice, But I will finish this plugin as fast as I can when I come Back! Sorry again!

- TheKillerTacos (TKRT)

**Comment by AndreTheGamer** [comment]
No delay will be needed. I will be working as hard as i can to finishe this and to release  the **PRE-ALPHA** :)

**Comment by TheKillerTacos** [comment]
Well, Cool, but i may be busy by now, so if you know how to make the plugin create a world, then it will be great, but then i will have to populate the chunks in the SkyWorld Generator, but ill do that later

**Comment by SkygridRex** [comment]
When you say populator you refer the trees in the world?

**Comment by TheKillerTacos** [comment]
@SkygridRex I guess. but ill be testing this a lot for the world generator, And now on, @SkygridRex @AndreTheGamer  @Skyladd You all now make Pull Request when adding code, but if its a Syntax error (like ; () {} and that stuff) just add it to the code Directly, since I will now start Checking this plugin and make a little plugin and Server for Direct Testing and Auto testing (like doing commands and checking the generators) but by now Make Pull Request when adding More code, if its config files add them Directly, Here a conclusion:

**Create Pull Request on:**
* Big changes (15 lines of code and up)
* Multiple File changing (When adding a lot of files and Modifying multiple ones)
* When Code is Really untested (Mostly if you think is buggy)

**When not create a Pull Request**
* On Config files (excluding Lang Files)
* On Small Syntax errors [Like () {} ; and etc]
* 14 or less lines of code Being modified/added/Changed
* Removing **UNNEEDED** Stuff
* Adding **CRITICAL** Stuff

And now ill start Creating this plugin (Got New Computer :D)

**Comment by SkygridRex** [comment]
Well

**Comment by TheKillerTacos** [comment]
The SkyBlockXT Development Resumes, I'm testing it and Fixing a lot of Syntax errors, In about 15m ill update the plugin in Here

**Comment by SkygridRex** [comment]
There's no problems with Tools folder, right? I say this for capital letter

**Comment by TheKillerTacos** [comment]
Nope. Not by now. Just a lot of Syntax errors with $bn  ($bn = "[SkyblockXT]";)

**Comment by SkygridRex** [comment]
So $bn same as SkyblockXT
